### DISCUSSION TITLE
Include fpm build support

### DISCUSSION THREAD

**Discussion by jalvesz** [Cambridge-ICCS/FTorch#77] [Ideas]
Hi, I just wanted to propose (and ask if there is interest on the maintainers side) to include support for building the project using fpm https://fpm.fortran-lang.org/

(I'm currently using your project that I build with CMake with a few tweaks but also like a lot the fpm workflow :) )

If so, I started playing with an fpm.toml at the root of the project (WARNING It doesn't work for the moment):

```toml
name = "FTorch"
version = "0.1.0"
license = "license"
author = "ICCS"
maintainer = "ICCS"
copyright = "Copyright 2019, Institute of Computing for Climate Science"

[library]
include-dir = ["<paht_to_libtorch>/libtorch/include","<paht_to_libtorch>/libtorch/include/torch","<paht_to_libtorch>/libtorch/include/c10/util","<paht>/libtorch-lin-shared-with-deps-2.1.1+cpu/libtorch/lib"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

external-modules = ["torch", "torch_cpu", "c10"]
link = ["torch", "torch_cpu", "c10"]

[install]
library = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
```
and this would need a command line such as:
```shell
export TORCH_INC="<paht_to_libtorch>/libtorch/include"
export TORCH_LIB="<paht_to_libtorch>/libtorch/lib"
fpm build --flag "-cpp -std=c++17 -I$TORCH_INC -L$TORCH_LIB"
```
For the moment I'm hitting an error with this approach:
```shell
././src/ctorch.cpp:2:10: fatal error: torch/torch.h: No such file or directory
    2 | #include <torch/torch.h>
```
Not sure yet why
